spring:
  mail:
    port: 8080
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_crud?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    hikari:
      max-lifetime: 120000

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.cloudfly.springboot.crud.pojo

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql

